id = "aurelia/window_count"
name = "Window Count"
version = "1.0.0"
plugin_api = 3
author = "Aurelia"
license = "MIT"
dependencies = []
tags = ["bar"]
icon = "window"
description = "Show number of windows (MangoWM only)"

[[widget]]
id = "widget"
entry = "widget.luau"

	[[widget.setting]]
	key = "direction"
	type = "select"
	options = [
		{ value = "Left", label_key = "left" },
		{ value = "All", label_key = "all" },
		{ value = "Right", label_key = "right" },
		{ value = "Position", label_key = "position" }
	]
	label_key = "settings.direction.label"
	description_key = "settings.direction.description"
	default = "All"

[[service]]
id = "service"
entry = "service.luau"
