id = "aurelia/window_count"
name = "Window Count"
version = "1.0.0"
plugin_api = 3
author = "Aurelia"
license = "MIT"
dependencies = ["node"]
tags = ["bar"]
icon = "window"
description = "Show number of windows (MangoWM only)"

[[widget]]
id = "widget"
entry = "widget.luau"

	[[widget.setting]]
	key = "direction"
	type = "select"
	options = [
		{ value = "left", label_key = "settings.direction.options.left" },
		{ value = "all", label_key = "settings.direction.options.all" },
		{ value = "right", label_key = "settings.direction.options.right" },
		{ value = "position", label_key = "settings.direction.options.position" }
	]
	label_key = "settings.direction.label"
	description_key = "settings.direction.description"
	default = "all"

[[service]]
id = "service"
entry = "service.luau"
