id = "noctalia/window_count"
name = "Window Count"
version = "1.0.0"
plugin_api = 5
author = "Aurelia"
license = "MIT"
dependencies = []
tags = ["bar"]
icon = "window"
description = "Show number of windows (MangoWM only)"

[[widget]]
id = "window_count"
entry = "widget.luau"

	[[widget.setting]]
	key = "direction"
	type = "select"
	options = ["Left", "All", "Right", "Position"]
	label_key = "settings.direction.label"
	description_key = "settings.direction.description"
	default = "All"

[[service]]
id = "service"
entry = "service.luau"
